version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: cyberbits-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cyberbits_crm
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: cyberbits-server
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=cyberbits_crm
      - DB_HOST=postgres
      - DB_PORT=5432
      - JWT_SECRET=cyberbits_secret_key
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: cyberbits-client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - server

volumes:
  postgres_data: 